### ISSUE TITLE
Title and descrition module

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Next-Site#31]
Please update the next site to have the title module as well

**Comment by MeanEYE** [comment]
That would require whole site upgrade.

**Comment by hanan-avzuk** [comment]
What does that mean?

**Comment by MeanEYE** [comment]
That means it's not just turning on something it means a lot of work to make the site work on newer version of Caracal. Since the old version doesn't have title and page description support. Not only that, site is hosted on their server so I would have to manually upload all the changes and then configure database to which I don't have access.

**Comment by hanan-avzuk** [comment]
When will this be done, Eli has the description module and need the title to come along with it

**Comment by MeanEYE** [comment]
Probably never without sitting and investing time to bring site to new version of Caracal which is not yet released.

**Comment by MeanEYE** [comment]
@hanan-avzuk while am messing around with templates, want me to upgrade the site to newer version of system and enable this module?

**Comment by hanan-avzuk** [comment]
Yes, I like Eli
